/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package action;

import java.sql.Date;

import idao.IBookDao;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import po.Book;
import form.addForm;


public class addAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	private IBookDao ibdao;
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		addForm addedForm = (addForm) form;// TODO Auto-generated method stub
		
		String bid = addedForm.getBid();
		String btype = addedForm.getBtype();
		String bauthor = addedForm.getBauthor();
		String bname = addedForm.getBname();
		int bprice = addedForm.getBprice();
		int bamount = addedForm.getBamount();
		Date bdate = addedForm.getBdate();
		Book book = new Book();
		book.setBamount(bamount);
		book.setBauthor(bauthor);
		book.setBprice(bprice);
		book.setBdate(bdate);
		book.setBtype(btype);
		book.setBid(bid);
		book.setBname(bname);
		
		int res = ibdao.add(book);
		if(res != 0) {
			request.setAttribute("msg", "add success.");
		} else {
			request.setAttribute("msg", "add fail.");
		}
		return new ActionForward("/add.jsp");
	}
	public IBookDao getIbdao() {
		return ibdao;
	}
	public void setIbdao(IBookDao ibdao) {
		this.ibdao = ibdao;
	}
}