/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package action;

import idao.ICustomerDao;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import po.Customer;
import form.LoginForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-08-2016
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="LoginForm" input="/login.jsp" scope="request" validate="true"
 */
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	private ICustomerDao icdao;
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LoginForm loginForm = (LoginForm) form;// TODO Auto-generated method stub
		String account = loginForm.getAccount();
		String password = loginForm.getPassword();
		
		Customer cus = icdao.getCustomerByAccount(account);
		if(cus != null && cus.getPassword().equals(password)) {
			request.setAttribute("msg", "welcome " + cus.getCname() + " login success.");
		} else {
			request.setAttribute("msg", "login fail.");
		}
		return new ActionForward("/login.jsp");
	}
	public ICustomerDao getIcdao() {
		return icdao;
	}
	public void setIcdao(ICustomerDao icdao) {
		this.icdao = icdao;
	}
}