/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package action;

import idao.IBookDao;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import form.updateForm;


public class updateAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	private IBookDao ibdao;
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		updateForm myForm = (updateForm) form;// TODO Auto-generated method stub
		
		String bid = myForm.getBid();
		int bamount = myForm.getBamount();
		
		int res = ibdao.update(bid, bamount);
		if(res != 0) {
			request.setAttribute("msg", "update success.");
		} else {
			request.setAttribute("msg", "update fail.");
		}
		return new ActionForward("/update.jsp");
	}
	public IBookDao getIbdao() {
		return ibdao;
	}
	public void setIbdao(IBookDao ibdao) {
		this.ibdao = ibdao;
	}
}